Repository Solvro/backend-wakacyjne-wyzwanie-2025, pull requests merged in 2025-08, with the labels that each got.

#4 fix: app module tests
  1. Podstawy API/solution/src/app.controller.spec.ts
  1. Podstawy API/solution/test/app.e2e-spec.ts
Labels: size/S

#5 Feat/bazy danych
  2. Bazy danych/2.md
Labels: size/M

#6 Feat/3 part
  3. CRUD i dokumentacja/3.md
Labels: size/S

#7 Feat: Part 4 - auth & validators
  .gitignore
  4. Autoryzacja i walidatory/4.md
  4. Autoryzacja i walidatory/solution/.env.example
  4. Autoryzacja i walidatory/solution/.gitignore
  4. Autoryzacja i walidatory/solution/README.md
  4. Autoryzacja i walidatory/solution/eslint.config.mjs
  4. Autoryzacja i walidatory/solution/nest-cli.json
  4. Autoryzacja i walidatory/solution/package-lock.json
  4. Autoryzacja i walidatory/solution/package.json
  4. Autoryzacja i walidatory/solution/prisma/migrations/20250804174247_init/migration.sql
  4. Autoryzacja i walidatory/solution/prisma/migrations/20250805181117_v1/migration.sql
  4. Autoryzacja i walidatory/solution/prisma/migrations/20250821103242_auth_fields/migration.sql
  4. Autoryzacja i walidatory/solution/prisma/migrations/20250821103305_auth_fields/migration.sql
  4. Autoryzacja i walidatory/solution/prisma/migrations/20250821103538_added_roles/migration.sql
  4. Autoryzacja i walidatory/solution/prisma/migrations/20250821110346_added_is_enabled/migration.sql
  4. Autoryzacja i walidatory/solution/prisma/migrations/20250821112042_user_table/migration.sql
  4. Autoryzacja i walidatory/solution/prisma/migrations/migration_lock.toml
  4. Autoryzacja i walidatory/solution/prisma/schema.prisma
  4. Autoryzacja i walidatory/solution/prisma/seed.ts
  4. Autoryzacja i walidatory/solution/src/app.controller.spec.ts
  4. Autoryzacja i walidatory/solution/src/app.controller.ts
  4. Autoryzacja i walidatory/solution/src/app.module.ts
  4. Autoryzacja i walidatory/solution/src/app.service.ts
  4. Autoryzacja i walidatory/solution/src/auth/auth.controller.spec.ts
  4. Autoryzacja i walidatory/solution/src/auth/auth.controller.ts
  4. Autoryzacja i walidatory/solution/src/auth/auth.guard.ts
  4. Autoryzacja i walidatory/solution/src/auth/auth.module.ts
  4. Autoryzacja i walidatory/solution/src/auth/auth.service.spec.ts
  4. Autoryzacja i walidatory/solution/src/auth/auth.service.ts
  4. Autoryzacja i walidatory/solution/src/auth/dto/login-response.dto.ts
  4. Autoryzacja i walidatory/solution/src/auth/dto/login.dto.ts
  4. Autoryzacja i walidatory/solution/src/auth/dto/request-with-user.dto.ts
  4. Autoryzacja i walidatory/solution/src/auth/roles/role.decorator.ts
  4. Autoryzacja i walidatory/solution/src/auth/roles/role.guard.ts
  4. Autoryzacja i walidatory/solution/src/database/database.module.ts
  4. Autoryzacja i walidatory/solution/src/database/database.service.ts
  4. Autoryzacja i walidatory/solution/src/main.ts
  4. Autoryzacja i walidatory/solution/src/trip/dto/create-trip-reponse.dto.ts
  4. Autoryzacja i walidatory/solution/src/trip/dto/create-trip.dto.ts
  4. Autoryzacja i walidatory/solution/src/trip/dto/update-trip.dto.ts
  4. Autoryzacja i walidatory/solution/src/trip/trip.controller.spec.ts
  4. Autoryzacja i walidatory/solution/src/trip/trip.controller.ts
  4. Autoryzacja i walidatory/solution/src/trip/trip.module.ts
  4. Autoryzacja i walidatory/solution/src/trip/trip.service.spec.ts
  4. Autoryzacja i walidatory/solution/src/trip/trip.service.ts
  4. Autoryzacja i walidatory/solution/src/user/dto/user-metadata.ts
  4. Autoryzacja i walidatory/solution/src/user/dto/user-update-response.dto.ts
  4. Autoryzacja i walidatory/solution/src/user/dto/user-update.dto.ts
  4. Autoryzacja i walidatory/solution/src/user/user.controller.ts
  4. Autoryzacja i walidatory/solution/src/user/user.module.ts
  4. Autoryzacja i walidatory/solution/src/user/user.service.ts
  4. Autoryzacja i walidatory/solution/src/validators/nice-text.validator.ts
  4. Autoryzacja i walidatory/solution/test/app.e2e-spec.ts
  4. Autoryzacja i walidatory/solution/test/jest-e2e.json
  4. Autoryzacja i walidatory/solution/tsconfig.build.json
  4. Autoryzacja i walidatory/solution/tsconfig.json
  4. Autoryzacja i walidatory/test_site/serve.ps1
  4. Autoryzacja i walidatory/test_site/test_site.html
Labels: size/XXL
